### ISSUE TITLE
Trouble activating extension redhat.vscode-xml

### ISSUE THREAD

**Issue by bjokr** [redhat-developer/vscode-xml#1020]
Hello,

I am trying to use this plugin to format a file as XML. However, as soon as I set language mode to XML using the language4 selector in the lower right corner of VSCode, I run into issues. In the extension host output, the following error appears:

2024-08-20 07:33:06.582 [error] Activating extension redhat.vscode-xml failed due to an error:
2024-08-20 07:33:06.582 [error] Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at Object.spawn (node:child_process:799:9)
	at c:\Users\username\.vscode\extensions\redhat.vscode-xml-0.27.1-win32-x64\dist\extension.js:2:552400
	at async x.createConnection (c:\Users\username\.vscode\extensions\redhat.vscode-xml-0.27.1-win32-x64\dist\extension.js:2:391359)
	at async x.start (c:\Users\username\.vscode\extensions\redhat.vscode-xml-0.27.1-win32-x64\dist\extension.js:2:382808)

And in the XML support output, a similar message appears, with the addition of the following at the very start of the message:

[Error - 7:33:06 AM] XML Support client: couldn't create connection to server.

Seems I am running into the same issue on two different Win11 machines. I am running the plugin in binary mode, as java is not really an option.

Any suggestion as to what causes this error and how it can be fixed would be greatly appreciated. Thanks.

**Comment by bjokr** [comment]
Seems I am unable to run lemminx-win32 due to security policies. Assuming this is the cause. Closing issue for now.

**Comment by bjokr** [comment]
Seems I am unable to run lemminx-win32 due to security policies. Assuming this is the cause. Closing issue for now.
