### ISSUE TITLE
cant get it to do anything (and there is no documentation on correct usage also)

### ISSUE THREAD

**Issue by prof7bit** [redhat-developer/vscode-xml#183]
Either the documentation is incomplete and missing to explain how to actually activate it or there is a bug and it won't do anything.

I have associated a file extension with a schema

    "xml.fileAssociations": [
        {
            "systemId": "http://www.io-link.com/IODD/2010/10/IODD1.1.xsd",
            "pattern": "**/*IODD1.1.xml"
        }
    ]

but if I load this file it won't do any validation, I can intentionally insert unknown tags or even syntactic errors and save the document but there is no indication that anything is being validated at all or anything with the configuration is wrong or that there are any errors in my xml document.

**Comment by prof7bit** [comment]
I'm also seeing lots of exceptions in lsp4xml.log

Sep 26, 2019 2:40:15 PM org.eclipse.lsp4xml.extensions.contentmodel.participants.diagnostics.XMLValidator doDiagnostics
SCHWERWIEGEND: Unexpected XMLValidator error
java.lang.NullPointerException
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.XMLSchemaErrorCode.toLSPRange(XMLSchemaErrorCode.java:171)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.diagnostics.LSPErrorReporterForXML.toLSPRange(LSPErrorReporterForXML.java:58)
	at org.eclipse.lsp4xml.services.extensions.diagnostics.AbstractLSPErrorReporter.internalToLSPRange(AbstractLSPErrorReporter.java:139)
	at org.eclipse.lsp4xml.services.extensions.diagnostics.AbstractLSPErrorReporter.reportError(AbstractLSPErrorReporter.java:80)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.reportSchemaWarning(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.getSchemaDocument1(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.getSchemaDocument(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.findSchemaGrammar(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.diagnostics.XMLValidator.doDiagnostics(XMLValidator.java:114)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.diagnostics.ContentModelDiagnosticsParticipant.doDiagnostics(ContentModelDiagnosticsParticipant.java:46)
	at org.eclipse.lsp4xml.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:83)
	at org.eclipse.lsp4xml.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:51)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:150)
	at org.eclipse.lsp4xml.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:159)
	at org.eclipse.lsp4xml.XMLTextDocumentService.validate(XMLTextDocumentService.java:434)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:427)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Sep 26, 2019 2:40:15 PM org.eclipse.lsp4xml.extensions.contentmodel.participants.diagnostics.XMLValidator doDiagnostics
SCHWERWIEGEND: Unexpected XMLValidator error
java.lang.NullPointerException
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.XMLSchemaErrorCode.toLSPRange(XMLSchemaErrorCode.java:171)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.diagnostics.LSPErrorReporterForXML.toLSPRange(LSPErrorReporterForXML.java:58)
	at org.eclipse.lsp4xml.services.extensions.diagnostics.AbstractLSPErrorReporter.internalToLSPRange(AbstractLSPErrorReporter.java:139)
	at org.eclipse.lsp4xml.services.extensions.diagnostics.AbstractLSPErrorReporter.reportError(AbstractLSPErrorReporter.java:80)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.reportSchemaWarning(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.getSchemaDocument1(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.getSchemaDocument(Unknown Source)
	at org.apache.xerces.impl.xs.traversers.XSDHandler.parseSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaLoader.loadSchema(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.findSchemaGrammar(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.diagnostics.XMLValidator.doDiagnostics(XMLValidator.java:114)
	at org.eclipse.lsp4xml.extensions.contentmodel.participants.diagnostics.ContentModelDiagnosticsParticipant.doDiagnostics(ContentModelDiagnosticsParticipant.java:46)
	at org.eclipse.lsp4xml.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:83)
	at org.eclipse.lsp4xml.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:51)
	at org.eclipse.lsp4xml.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:150)
	at org.eclipse.lsp4xml.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:159)
	at org.eclipse.lsp4xml.XMLTextDocumentService.validate(XMLTextDocumentService.java:434)
	at org.eclipse.lsp4xml.XMLTextDocumentService.lambda$triggerValidationFor$23(XMLTextDocumentService.java:427)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by angelozerr** [comment]
Could you share your XML file please.

**Comment by prof7bit** [comment]
[IO-Link-01-DirectParamsDevice-20130515-IODD1.1.zip](https://github.com/redhat-developer/vscode-xml/files/3657949/IO-Link-01-DirectParamsDevice-20130515-IODD1.1.zip)

**Comment by prof7bit** [comment]
I am on Ubuntu Linux:

```
bernd@bernd:~/.lsp4xml $ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

bernd@bernd:~/.lsp4xml $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
bernd@bernd:~/.lsp4xml $ 

```

**Comment by angelozerr** [comment]
Thank you, I can reproduce your NPE problem. I will investigate your problem.

**Comment by angelozerr** [comment]
@prof7bit after studying your usecase, I have found 2 little bugs that I will fix it, but you can benefit with validation and completion.

At first you don't need xml.fileAssociation since you bind your XML with XML Schema (according your sample): 

```xml
<IODevice xmlns="http://www.io-link.com/IODD/2010/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.io-link.com/IODD/2010/10 IODD1.1.xsd">

```

This declaration means that you have the XML Schema `IODD1.1.xsd` in the same folder than your XML file. 

If you unzip the following folder
[io-link-xml.zip](https://github.com/redhat-developer/vscode-xml/files/3663859/io-link-xml.zip)

you can open your the XML file of the folder and validation, completion, hover, etc should work.

![IOLInkDemo](https://user-images.githubusercontent.com/1932211/65788469-6ee0a380-e15b-11e9-94b7-a802204ad975.gif)

Normaly, you could write too:

```xml
<IODevice xmlns="http://www.io-link.com/IODD/2010/10" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.io-link.com/IODD/2010/10 https://io-link.com/IODD/2010/10/IODD1.1.xsd">

```

To bind your XML file with https://io-link.com/IODD/2010/10/IODD1.1.xsd but validation , completion doesn't work because:

 * this XML Schema includes https://io-link.com/IODD/2010/10/IODD-Primitives1.1.xsd which imports xml.xsd `<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>` which is wrong because `https://io-link.com/IODD/2010/10/xml.xsd` doesn't exists (you should see this error on the root). LSP4XML manages a cache in .lsp4xml folder (by default in your home folder) and if you copy/paste the xml.xsd file (that you can see in the attached zip) validation should work. But completion will not work since there is a bug that I must fix it (completion should use XML Schema from cache).

You could write your own XML catalog too to avoid setting your XSD files in the same folder your XML files. I suggest you that you read documentation about XML catalogs.

**Comment by angelozerr** [comment]
> I will prepare an another PR for completion cache bug.

Done with https://github.com/angelozerr/lsp4xml/pull/570
