### ISSUE TITLE
OOM Error when using an lemminx extension to register xsd support.

### ISSUE THREAD

**Issue by rzgry** [redhat-developer/vscode-xml#317]
We are using a lemminx extension to register this xsd file using a URIResolverExtension https://github.com/OpenLiberty/open-liberty-tools/blob/integration/dev/com.ibm.ws.st.core/server.xsd

After playing around with a server.xml file and testing the completion in different element (maybe 20-30 completion requests). The completion request will get stuck at "Loading" and generates a bunch of heapdump / javacore files in the project directory.

Setting the vmargs setting to this seems to fix it.
```
"xml.server.vmargs": "-noverify -Xmx1024M -XX:+UseG1GC -XX:+UseStringDeduplication",
```

Example log: 
```
Aug. 28, 2020 10:37:38 A.M. org.eclipse.lemminx.XMLLanguageServer initialize
INFO: Initializing XML Language server
LemMinX Server info:
 - Version : 0.13.1
 - Java : /Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jdk/Contents/Home
 - Git 3c6c0de - [maven-release-plugin] prepare release 0.13.1
[Warn  - 10:38:11 a.m.] Aug. 28, 2020 10:38:11 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation()
Message: Unmatched cancel notification for request id 33
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/08/28 10:39:23 - please wait.
JVMDUMP032I JVM requested System dump using '/Users/rzegray/Desktop/demo/core.20200828.103923.23477.0001.dmp' in response to an event
JVMDUMP012E Error in System dump: The core file created by child process with pid = 23724 was not found. Expected to find core file with name "/cores/core.23724"
JVMDUMP032I JVM requested Heap dump using '/Users/rzegray/Desktop/demo/heapdump.20200828.103923.23477.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /Users/rzegray/Desktop/demo/heapdump.20200828.103923.23477.0002.phd
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/08/28 10:39:29 - please wait.
JVMDUMP032I JVM requested Java dump using '/Users/rzegray/Desktop/demo/javacore.20200828.103923.23477.0003.txt' in response to an event
JVMDUMP010I Java dump written to /Users/rzegray/Desktop/demo/javacore.20200828.103923.23477.0003.txt
JVMDUMP032I JVM requested Snap dump using '/Users/rzegray/Desktop/demo/Snap.20200828.103923.23477.0005.trc' in response to an event
JVMDUMP010I Snap dump written to /Users/rzegray/Desktop/demo/Snap.20200828.103923.23477.0005.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
JVMDUMP032I JVM requested Heap dump using '/Users/rzegray/Desktop/demo/heapdump.20200828.103929.23477.0004.phd' in response to an event
JVMDUMP010I Heap dump written to /Users/rzegray/Desktop/demo/heapdump.20200828.103929.23477.0004.phd
JVMDUMP032I JVM requested Java dump using '/Users/rzegray/Desktop/demo/javacore.20200828.103929.23477.0006.txt' in response to an event
JVMDUMP010I Java dump written to /Users/rzegray/Desktop/demo/javacore.20200828.103929.23477.0006.txt
JVMDUMP032I JVM requested Snap dump using '/Users/rzegray/Desktop/demo/Snap.20200828.103929.23477.0007.trc' in response to an event
JVMDUMP010I Snap dump written to /Users/rzegray/Desktop/demo/Snap.20200828.103929.23477.0007.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
[Error - 10:39:29 a.m.] Aug. 28, 2020 10:39:29 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError()
Message: Internal error: java.lang.OutOfMemoryError: Java heap space
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/sun.text.resources.cldr.FormatData.getContents(FormatData.java:192)
	at java.base/java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:195)
	at java.base/java.util.ListResourceBundle.handleKeySet(ListResourceBundle.java:168)
	at java.base/java.util.ResourceBundle.containsKey(ResourceBundle.java:2305)
	at java.base/sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(LocaleResources.java:191)
	at java.base/java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:628)
	at java.base/java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
	at java.base/sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
	at java.base/java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
	at java.base/java.util.Formatter.getZero(Formatter.java:2437)
	at java.base/java.util.Formatter.<init>(Formatter.java:1956)
	at java.base/java.util.Formatter.<init>(Formatter.java:1994)
	at java.base/java.io.PrintWriter.format(PrintWriter.java:991)
	at java.base/java.io.PrintWriter.printf(PrintWriter.java:889)
	at com.overzealous.remark.convert.Anchor.handleNode(Anchor.java:56)
	at com.overzealous.remark.convert.DocumentConverter.walkNodes(DocumentConverter.java:323)
	at com.overzealous.remark.convert.Paragraph.handleNode(Paragraph.java:36)
	at com.overzealous.remark.convert.DocumentConverter.walkNodes(DocumentConverter.java:323)
	at com.overzealous.remark.convert.DocumentConverter.convertImpl(DocumentConverter.java:265)
	at com.overzealous.remark.convert.DocumentConverter.convert(DocumentConverter.java:232)
	at com.overzealous.remark.Remark.processConvert(Remark.java:367)
	at com.overzealous.remark.Remark.convert(Remark.java:342)
	at com.overzealous.remark.Remark.convert(Remark.java:305)
	at com.overzealous.remark.Remark.convert(Remark.java:291)
	at org.eclipse.lemminx.utils.MarkdownConverter.convert(MarkdownConverter.java:75)
	at org.eclipse.lemminx.utils.MarkupContentFactory.createMarkupContent(MarkupContentFactory.java:48)
	at org.eclipse.lemminx.extensions.contentmodel.utils.XMLGenerator.createMarkupContent(XMLGenerator.java:285)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.addCompletionItem(ContentModelCompletionParticipant.java:246)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.fillWithChildrenElementDeclaration(ContentModelCompletionParticipant.java:182)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.fillWithPossibleElementDeclaration(ContentModelCompletionParticipant.java:145)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.onTagOpen(ContentModelCompletionParticipant.java:80)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:627)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:752)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:210)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:145)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:192)
	at org.eclipse.lemminx.XMLTextDocumentService$$Lambda$101/0000000000000000.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more

[Error - 10:39:29 a.m.] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1238)
	at java.base/java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1205)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/sun.text.resources.cldr.FormatData.getContents(FormatData.java:192)
	at java.base/java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:195)
	at java.base/java.util.ListResourceBundle.handleKeySet(ListResourceBundle.java:168)
	at java.base/java.util.ResourceBundle.containsKey(ResourceBundle.java:2305)
	at java.base/sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(LocaleResources.java:191)
	at java.base/java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:628)
	at java.base/java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
	at java.base/sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
	at java.base/java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
	at java.base/java.util.Formatter.getZero(Formatter.java:2437)
	at java.base/java.util.Formatter.<init>(Formatter.java:1956)
	at java.base/java.util.Formatter.<init>(Formatter.java:1994)
	at java.base/java.io.PrintWriter.format(PrintWriter.java:991)
	at java.base/java.io.PrintWriter.printf(PrintWriter.java:889)
	at com.overzealous.remark.convert.Anchor.handleNode(Anchor.java:56)
	at com.overzealous.remark.convert.DocumentConverter.walkNodes(DocumentConverter.java:323)
	at com.overzealous.remark.convert.Paragraph.handleNode(Paragraph.java:36)
	at com.overzealous.remark.convert.DocumentConverter.walkNodes(DocumentConverter.java:323)
	at com.overzealous.remark.convert.DocumentConverter.convertImpl(DocumentConverter.java:265)
	at com.overzealous.remark.convert.DocumentConverter.convert(DocumentConverter.java:232)
	at com.overzealous.remark.Remark.processConvert(Remark.java:367)
	at com.overzealous.remark.Remark.convert(Remark.java:342)
	at com.overzealous.remark.Remark.convert(Remark.java:305)
	at com.overzealous.remark.Remark.convert(Remark.java:291)
	at org.eclipse.lemminx.utils.MarkdownConverter.convert(MarkdownConverter.java:75)
	at org.eclipse.lemminx.utils.MarkupContentFactory.createMarkupContent(MarkupContentFactory.java:48)
	at org.eclipse.lemminx.extensions.contentmodel.utils.XMLGenerator.createMarkupContent(XMLGenerator.java:285)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.addCompletionItem(ContentModelCompletionParticipant.java:246)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.fillWithChildrenElementDeclaration(ContentModelCompletionParticipant.java:182)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.fillWithPossibleElementDeclaration(ContentModelCompletionParticipant.java:145)
	at org.eclipse.lemminx.extensions.contentmodel.participants.ContentModelCompletionParticipant.onTagOpen(ContentModelCompletionParticipant.java:80)
	at org.eclipse.lemminx.services.XMLCompletions.collectOpenTagSuggestions(XMLCompletions.java:627)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:752)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:210)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:145)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$1(XMLTextDocumentService.java:192)
	at org.eclipse.lemminx.XMLTextDocumentService$$Lambda$101/0000000000000000.apply(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1236)
	... 7 more
```

**Comment by fbricon** [comment]
Looks like we may have a memory leak. @rzgry any chance you can do some profiling?

**Comment by rzgry** [comment]
After doing some quick testing it also seems like this does not occur if I register the xsd using the xml fileAssociations setting instead. 
```
  "xml.fileAssociations": [
    {
      "pattern": "**/*/server.xml",
      "systemId": "/Users/rzegray/Desktop/server.xsd"
    }
  ]
```

Seems to only OOM if it is registered using a URIResolverExtension.

**Comment by angelozerr** [comment]
> Seems to only OOM if it is registered using a URIResolverExtension.

That's strange. If you implement URIResolverExtension like XSL it should work.

Please:

 * share your extension in order to I play and debug it.
 * explain your usecase (give me your server.xml file + explain where you open completion).

Thanks.

**Comment by rzgry** [comment]
Fixed with https://github.com/OpenLiberty/liberty-language-server/pull/6
