### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by erichiller** [redhat-developer/vscode-xml#602]
I receive `Connection to server got closed. Server will not be restarted.` in the XML Extension Output window when opening an XML file.

XML Extension Output:
```
[Info - 7:23:26 AM] Oct 09, 2021 07:23:26 org.eclipse.lemminx.XMLLanguageServer initialize()
Message: Initializing XML Language server
LemMinX Server info:
 - Version : 0.18.0
 - Native Image
 - VM Version : 1.8.0_272
 - Git [Branch 61ac76820f1a87405a75530a054e40e63dbf18e4] 61ac768 - [maven-release-plugin] prepare release 0.18.0
[Error - 7:23:26 AM] Connection to server got closed. Server will not be restarted.
```

Extension Host Output:
```
[exthost] [error] Error: Connection to server got closed. Server will not be restarted.
at E.handleConnectionClosed (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:342368)
at E.handleConnectionClosed (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:402460)
at t (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:340143)
at invoke (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:456147)
at o.fire (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:456908)
at Y (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:443791)
at invoke (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:456147)
at o.fire (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:456908)
at g.fireClose (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:468364)
at Socket.<anonymous> (/home/eric/.vscode/extensions/redhat.vscode-xml-0.18.0/dist/extension.js:2:469149)
at Socket.emit (events.js:315:20)
at Socket.EventEmitter.emit (domain.js:467:12)
at Pipe.<anonymous> (net.js:673:12)
```

VSCode Version:
```
Version: 1.60.2
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:01:43.795Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-37-generic
```

OS: Ubuntu 21.04

Let me know if you need any more information.

**Comment by AnSch1510** [comment]
I've getting the same error when editing the .xsd file. It seems that the validation of a new -not yet correctly written- entry goes wrong.

**Comment by angelozerr** [comment]
@erichiller @AnSch1510 could you share please XML or XSD which causes this problem.

**Comment by AnSch1510** [comment]
I've downloaded the file `http://www.w3.org/2001/xml.xsd` to `/home/deuta/.lemminx/cache/http/www.w3.org/2001/` via

```bash
cd /home/deuta/.lemminx/cache/http/www.w3.org/2001/
wget http://www.w3.org/2001/xml.xsd
```

now it seems to work for me...

**Comment by angelozerr** [comment]
@rgrunber do you think with your fixes, we can close this issue?

**Comment by rgrunber** [comment]
Yes, we can close this. Looks like we addressed the original issue, and the other as well.
