### ISSUE TITLE
Exception when "XML: Revalidate all opened XML files"

### ISSUE THREAD

**Issue by joe914** [redhat-developer/vscode-xml#675]
[Info  - 10:00:38]  12, 2022 10:00:38 org.eclipse.lemminx.XMLLanguageServer initialize()
Message: Initializing XML Language server
LemMinX Server info:
 - Version : **0.19.1**
 - Java : C:\Program Files\Java\jre1.8.0_321
 - VM Version : **1.8.0_321**
 - Git 6059965 - [maven-release-plugin] prepare release 0.19.1
[Error - 10:00:50]  12, 2022 10:00:50 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError()
Message: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: **No command handler for the command: xml.validation.all.files**
	at org.eclipse.lemminx.XMLWorkspaceService.executeCommand(XMLWorkspaceService.java:62)
	... 16 more

**Comment by angelozerr** [comment]
I cannot reproduce it.

Coul you explain how you obtain this error. I have the impression thatyou try to revalidate all xml files when XML language server is starting.

**Comment by joe914** [comment]
I cannot reproduce it and closed it. Thanks.
