### ISSUE TITLE
Cannot use xsd to validate xml file

### ISSUE THREAD

**Issue by joe914** [redhat-developer/vscode-xml#676]
All files are in the same directory. 

The extension is enabled, but no error in foo.xml and foo2.xml  ???

![1647145235(1)](https://user-images.githubusercontent.com/93459145/158044918-a791dd35-3333-4c5d-adf8-9d0b406f4559.png)

**Comment by angelozerr** [comment]
Do you benefit with syntax validation? Ex the start and end tag are not the same

**Comment by joe914** [comment]
@angelozerr Thanks for your immediate response. It's ok two months ago and just now I tried the older vscode(vesion 1.63.2).

1. Extension works OK for foo.xsd, but failed for foo.xml and foo2.xml:
![1647161608(1)](https://user-images.githubusercontent.com/93459145/158052359-2429eecd-57d7-4880-b398-9134df5dab43.png)

2. The following processs is running:
c:\Users\user\.vscode\extensions\redhat.vscode-xml-0.19.1\server\lemminx-win32.exe

3. Output of "XML Support":
 Mar 13, 2022 04:40:45 org.eclipse.lemminx.XMLLanguageServer initialize()
Message: Initializing XML Language server
LemMinX Server info:
 - Version : 0.19.1
 - Native Image
 - VM Version : 11.0.9
 - Git [Branch 6059965ad91cd67cba1c91f4b82714c57dc64fa5] 6059965 - [maven-release-plugin] prepare release 0.19.1
 
4. Output of "Log(Extension Host)":
[2022-03-13 16:40:46.589] [exthost] [warning] [redhat.vscode-xml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[xml]', provide the URI of a resource or 'null' for any resource.
[2022-03-13 16:43:51.555] [exthost] [error] [redhat.vscode-xml] provider FAILED
[2022-03-13 16:43:51.768] [exthost] [error] Canceled: Canceled
    at S.makeCancelError (c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:2666:24)
    at S.handleFailedRequest (c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:2656:28)
    at c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:1058:39
    at m.provideDocumentHighlights (c:\Users\mayn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:171454)
[2022-03-13 16:43:51.910] [exthost] [error] [redhat.vscode-xml] provider FAILED
[2022-03-13 16:43:51.910] [exthost] [error] Canceled: Canceled
    at S.makeCancelError (c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:2666:24)
    at S.handleFailedRequest (c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:2656:28)
    at c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:1058:39
    at m.provideDocumentHighlights (c:\Users\mayn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:171454)
[2022-03-13 16:44:09.737] [exthost] [error] [redhat.vscode-xml] provider FAILED
[2022-03-13 16:44:09.737] [exthost] [error] Canceled: Canceled
    at S.makeCancelError (c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:2666:24)
    at S.handleFailedRequest (c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:2656:28)
    at c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:1115:39
    at s.provideDocumentSymbols (c:\Users\mayn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:167312)
[2022-03-13 16:44:15.331] [exthost] [error] [redhat.vscode-xml] provider FAILED
[2022-03-13 16:44:15.331] [exthost] [error] Canceled: Canceled
    at S.makeCancelError (c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:2666:24)
    at S.handleFailedRequest (c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:2656:28)
    at c:\Users\mayn\.vscode\extensions\redhat.vscode-xml-0.19.1\node_modules\vscode-languageclient\lib\common\client.js:1115:39
    at s.provideDocumentSymbols (c:\Users\mayn\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:167312)

**Comment by joe914** [comment]
continued(vscode v1.162.3 and extension v0.19.1)

I tried many times, extension is ok if(either):
1. disabled when startup vscode: enable extension
2. enabled when startup vscode: disable extension, reload vscode, enable extension

next: I will upgrade vscode to the new version and try again.

**Comment by joe914** [comment]
vscode v1.64.2 / extension v0.19.1, vscode v1.64.2 / extension v0.18.0 are the same as above (vscode v1.62.3 and extension v0.19.1, only work when enable again after startuping vscode ).

This extension always failed to work when using the latest vscode v1.65.2, even after disabled/reload/enable.

**Comment by angelozerr** [comment]
Many thanks for your detailed feedback.

Could you enable xml trace https://github.com/redhat-developer/vscode-xml/blob/master/docs/Troubleshooting.md#no-support-on-xml-file and share your trace please

**Comment by joe914** [comment]
version: vscode v1.64.2 / extension v0.18.0
[enabled_when_startup_vscode(failed).txt](https://github.com/redhat-developer/vscode-xml/files/8239342/enabled_when_startup_vscode.failed.txt)
[enable_after_startup_vscode(ok).txt](https://github.com/redhat-developer/vscode-xml/files/8239343/enable_after_startup_vscode.ok.txt)

**Comment by joe914** [comment]
version: vscode v1.65.2 / extension v0.18.0 ( "xml.server.preferBinary": false)
[enabled_when_startup_vscode(failed v1.65.2).txt](https://github.com/redhat-developer/vscode-xml/files/8239362/enabled_when_startup_vscode.failed.v1.65.2.txt)
[enable_after_startup_vscode(failed v1.65.2).txt](https://github.com/redhat-developer/vscode-xml/files/8239363/enable_after_startup_vscode.failed.v1.65.2.txt)

**Comment by angelozerr** [comment]
I'm a little lost I tried with vscode 1.65.2 and vscode-xml 0.19.1 and it seems it's working well.

Could you give me the XML/XSD content that you are trying please in the issue.

**Comment by angelozerr** [comment]
> [enable_after_startup_vscode(failed v1.65.2).txt](https://github.com/redhat-developer/vscode-xml/files/8239363/enable_after_startup_vscode.failed.v1.65.2.txt)

I have the impression that didOpen of your foo.xml is never called?

**Comment by angelozerr** [comment]
Do you think you could have some other installed xml extension. The main problem that I see is that didOpen is never called for xml file. After that you have à lot of bugs like diagnostics is not done when you open the xml file.

Xsd have disOpen request it is the reason why it works properly.

It us the reason why I suspect an another vscode extension which forbids didOpen

**Comment by joe914** [comment]
Find the cause of the prolem, the following setting in vscode setting.json:
  "files.associations": {
    "*.xml": "html"
  },

It will be ok after the above setting is removed, even for vscode v1.65.2.

@angelozerr Thank you very much for your help.
