### ISSUE TITLE
vscode-xml does not activate when opening an XML file

### ISSUE THREAD

**Issue by Erwyn** [redhat-developer/vscode-xml#879]
I have a weird behaviour. I've seen in the repository that the `onLanguage` is effectively set on xml but for whatever reason, if I open an XML file and look for the extension I have a `Not yet activated` and don't see it in the activated extensions neither.

I tried to disable all extensions and only activate this one without any success. I have nothing that refers to xml in my settings json.

**Comment by fbricon** [comment]
What OS are you on?
Do you see "XML Support" in the output tab?

**Comment by angelozerr** [comment]
@Erwyn could you check that your XML file is mapped with XML language. You can see that on the bottom toolbar

![image](https://user-images.githubusercontent.com/1932211/220948729-49407e10-3aa3-4272-a3ae-69d92f909ab2.png)

Could you share your XML please.

**Comment by Erwyn** [comment]
so, it is set on XML:

![image](https://user-images.githubusercontent.com/206743/220965149-0c41da9d-8c43-4fdf-b793-c2cbd63b7674.png)

And here is a simple file reproducing the issue:

[simple.tar.gz](https://github.com/redhat-developer/vscode-xml/files/10815783/simple.tar.gz)

The extension used to work, but sadly I can't say what changed in between.

**Comment by Erwyn** [comment]
I just looked at the Output, wasn't aware of this tab. I think I got something interesting in the `Extension Host` part:

```
2023-02-23 15:47:46.369 [error] Error: Header must provide a Content-Length property.
    at h.onData (/home/mgoyot/.vscode/extensions/redhat.vscode-xml-0.24.0-linux-x64/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/common/messageReader.js:137:27)
    at Socket.<anonymous> (/home/mgoyot/.vscode/extensions/redhat.vscode-xml-0.24.0-linux-x64/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/common/messageReader.js:121:18)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by Erwyn** [comment]
I went the `"xml.server.preferBinary": true` way. It works now, thank you very much !
